blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/kbrdn1/kbrdn.dev/blob/main/README.md
    about: Check our documentation before opening an issue
  - name: Contributing Guidelines
    url: https://github.com/kbrdn1/kbrdn.dev/blob/main/CONTRIBUTING.md
    about: Please read our contributing guidelines
