name: Tests

on: [push]

env:
  CI: true

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    # BASE
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8.2.0

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-version'

    - name: Install dependencies
      run: pnpm install

    - name: Lint code
      run: pnpm run lint

    - name: Build website
      run: pnpm run build